-- MySQL Script generated by MySQL Workbench
-- Сб. 29 нояб. 2014 17:03:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema photoAlbum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `photoAlbum` ;
CREATE SCHEMA IF NOT EXISTS `photoAlbum` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `photoAlbum` ;

-- -----------------------------------------------------
-- Table `photoAlbum`.`PhotoCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photoAlbum`.`PhotoCard` ;

CREATE TABLE IF NOT EXISTS `photoAlbum`.`PhotoCard` (
  `idPhotoCard` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  `photo` LONGBLOB NULL,
  PRIMARY KEY (`idPhotoCard`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
